version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    ports:
      - "80:3000"
  # db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: api_db
